{
    "name": "CV Repository",
    "version": "17.0.1.0.0",
    "category": "Human Resources",
    "summary": "Internal CV and candidate repository for administrators",
    "depends": ["base", "mail", "cv_ai"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/server_actions.xml",
        "wizard/upload_cv_wizard_views.xml",
        "wizard/reject_candidate_wizard_views.xml",
        "views/cv_batch_views.xml",
        "views/cv_document_views.xml",
        "views/candidate_views.xml",
        "views/processing_log_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
